#pragma once

#define ASSISTANT_CMD_SYNC_GROUPS       1
#define ASSISTANT_CMD_WEATHER_TODAY     2
#define ASSISTANT_CMD_WEATHER_TOMORROW  3
#define ASSISTANT_CMD_SET_TIMER         4
#define ASSISTANT_CMD_STOP              5
#define ASSISTANT_CMD_TIME_NOW          6
#define ASSISTANT_CMD_TIME_IN_LOCATION  7
#define ASSISTANT_CMD_VOLUME_UP_BASE    20
#define ASSISTANT_CMD_VOLUME_DOWN_BASE  30
#define ASSISTANT_CMD_VOLUME_STEP_COUNT 10
#define ASSISTANT_CMD_GROUP_BASE        100
